prj/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('result/', views.form_valid, name = 'form_valid'),
    path('input/', views.input, name = 'Input_View'),
    path('howtouse/', views.HowtoUse_View, name = 'HowtoUse_View'),
    path('user/', views.User_View, name = 'User_View'),
    path('database/', views.database, name='database'),
    path('nowloading/',views.nowloading, name='nowloading'),
    path('database/delete', views.delete, name='delete'),
]

prj/prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prj/myapp/models.py
from django.db import models
import hashlib
import os.path
from .name import NAME
# Create your models here.

# class Photo(models.Model):
#     title = models.CharField(null=True,max_length = 50)
#     image = models.ImageField(upload_to=get_image_path())
#     def get_filename(self):
#         return os.path.basename(self.file.name)
#########

def get_image_path(self, filename):
    """カスタマイズした画像パスを取得する.

    :param self: インスタンス (models.Model)
    :param filename: 元ファイル名
    :return: カスタマイズしたファイル名を含む画像パス
    """
    prefix = 'images/'
    name = 'image'
    extension = os.path.splitext(filename)[-1]
    return prefix + name + extension

def delete_previous_file(function):
    """不要となる古いファイルを削除する為のデコレータ実装.

    :param function: メイン関数
    :return: wrapper
    """
    def wrapper(*args, **kwargs):
        """Wrapper 関数.

        :param args: 任意の引数
        :param kwargs: 任意のキーワード引数
        :return: メイン関数実行結果
        """
        self = args[0]

        # 保存前のファイル名を取得
        result = Photo.objects.filter(pk=self.pk)
        previous = result[0] if len(result) else None
        path = '/Users/yuhi/django/prj/media/images' + '/' + 'image.jpg'
        path2 = '/Users/yuhi/django/prj/media/images' + '/' + 'image.png'
        if os.path.exists(path):
            os.remove('/Users/yuhi/django/prj/media/images' + '/' + 'image.jpg')
        if os.path.exists(path2):
            os.remove('/Users/yuhi/django/prj/media/images' + '/' + 'image.png')
        super(Photo, self).save()

        # 関数実行
        result = function(*args, **kwargs)


        return result
    return wrapper

class Photo(models.Model):
    @delete_previous_file
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super(Photo, self).save()

    @delete_previous_file
    def delete(self, using=None, keep_parents=False):
        super(Photo, self).delete()

    image = models.ImageField('画像', upload_to=get_image_path)


class Alcohol(models.Model):
    DEGREE_CHOICES = (
        ('', '度数を選択してください。'),
        (3, '3%'),
        (4, '4%'),
        (5, '5%'),
        (6, '6%'),
        (7, '7%'),
        (8, '8%'),
        (10, '10%'),
        (12, '12%'),
        (14, '14%'),
        (15, '15%'),
        (17, '17%'),
        (20, '20%'),
        (25, '25%'),
        (30, '30%'),
        (35, '35%'),
        (40, '40%'),
        (45, '45%'),
    )
    VALUE_CHOICES = (
        ('','量(サイズ)を選択してください。'),
        (180, '180ml(1合分)'),
        (200, '200ml(コップ1杯分)'),
        (350, '350ml(通常の1缶分)'),
        (500, '500ml(縦長の1缶分)'),
        (750, '750ml(4合瓶)'),
        (1800, '1800ml(1小瓶)'),
    )
    name = models.CharField(max_length=20, default = NAME)
    degree = models.IntegerField(default=0,choices=DEGREE_CHOICES) #百分率(%)でアルコール濃度の入力
    value = models.IntegerField(default=0,choices=VALUE_CHOICES) #飲んだ量(ml)
    #number = models.IntegerField(default=0) #飲んだ本数(本)
    #user_id = models.IntegerField() #user ID
class InfoUser(models.Model):
    # nickname = models.CharField(max_length=20)
    age = models.IntegerField()
    weight = models.IntegerField()

prj/myapp/forms.py
from django import forms
from .models import Alcohol
from .models import InfoUser

class PhotoForm(forms.Form):
    image = forms.ImageField()

class AlcoholData(forms.ModelForm):
    class Meta:
        model = Alcohol
        fields = ['name', 'degree', 'value'] #user_id消去済み

class WeightForm(forms.ModelForm):
    class Meta:
        model = InfoUser
        fields = ['age', 'weight']

prj/myapp/views.py
from django.shortcuts import render, redirect
from .models import Photo
from .forms import PhotoForm
from django.http import HttpResponse
from .models import Alcohol #models.pyのimport
from .forms import AlcoholData #forms.pyのAlcoholData()のimport
from .forms import WeightForm #追記ver2
from .models import InfoUser #追記ver3!!!!!!!
from time import sleep
from .name import NAME

#機械学習用
import sys
import cv2
import tensorflow as tf
import os
import random
import numpy as np
from . import main

# 識別ラベルと各ラベル番号に対応する名前
DRINK_NAMES = {
  0: u"ビール",
  1: u"赤ワイン",
  2: u"白ワイン"
}

def home(req):
    f = open('./name.py', 'w')
    f.write("NAME = \"\" ")
    f.close()
    if req.method == 'GET':
        return render(req, 'myapp/home.html', {
            'form': PhotoForm(),
        })

    elif req.method == 'POST':
        form = PhotoForm(req.POST, req.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        photo = Photo()
        photo.image = form.cleaned_data['image']
        photo.save()
        return redirect('/myapp/result')

# def Input_View(req):
#     return render(req, 'myapp/home.html')

def HowtoUse_View(req):
    return render(req, 'myapp/howtouse.html')

def User_View(req):
    params = {
        'title': '体重などのユーザデータ情報',
        'form_weight': WeightForm(),
        'user_info': [],
    }
    if(req.method == 'POST'):
        obj = InfoUser()
        user_info = WeightForm(req.POST, instance=obj)
        # if not user_info.is_valid():
        #     raise ValueError('invalid form')
        user_info.save()
        return redirect( '/myapp/home')
    return render(req,'myapp/user.html', params)

def nowloading(req):
    return render(req, 'myapp/nowloading.html')





def form_valid(request):

    image = []
    img = cv2.imread("//Users/yuhi/django/prj/media/images/image.jpg", cv2.IMREAD_COLOR)
    img = cv2.resize(img, (28, 28))
    image.append(img.flatten().astype(np.float32)/255.0)
    image = np.asarray(image)
    logits = main.inference(image, 1.0)
    sess = tf.InteractiveSession()
    saver = tf.train.Saver()
    sess.run(tf.initialize_all_variables())
    ckpt_path = '/Users/yuhi/django/prj/myapp/model.ckpt'
    if ckpt_path:
        saver.restore(sess, ckpt_path)
    softmax = logits.eval()
    result = softmax[0]
    rates = [round(n * 100.0, 1) for n in result]
    humans = []
    for i, rate in enumerate(rates):
        name = DRINK_NAMES[i]
        humans.append({
            'label': i,
            'name': name,
            'rate': rate
        })

    rank = sorted(humans, key=lambda x: x['rate'], reverse=True)
    rank2 = rank[0]
    rank3 = rank2['name'] #順番に並べたやつから名前を取り出す
    # 推論した結果を、テンプレートへ渡して表示
    context = {
        'result':rank3,
    }

    f = open('/Users/yuhi/django/prj/myapp/name.py', 'w')
    f.write("NAME = '"+ rank3 +"'")
    f.close()

    return redirect( '/myapp/nowloading')
    # return render(request,'myapp/inputform.html', context)

def input(request):
    if(request.method == 'POST'):
        obj = Alcohol()
        alcohol = AlcoholData(request.POST, instance=obj)
        alcohol.save()
        return redirect('/myapp/database')

    params = {
        'title': 'ホームページ',
        'form': AlcoholData(),
        'result':NAME,
    }
    return render(request, 'myapp/inputform.html', params)


def delete(request):
    Alcohol.objects.all().delete()
    return redirect('/myapp/database')#ここはパスを指定

def database(request):
    params = {
        'title': 'データベース情報',
        'message': 'データベースの全データです。',
        'condition': '',
        'data': [],
        'detail1': '',
        'detail2': '',
        'detail3': '',
        'detail4': '',
    }

    params['data'] = Alcohol.objects.all()
    alcohol_data = Alcohol.objects.all()
    user_info = InfoUser.objects.all().last()
    intake_alcohol = 0.0

    for item in alcohol_data:
        intake_alcohol += item.degree*float(item.value)

    intake_alcohol *= 0.8 #アルコール比重


    result = intake_alcohol /100.0 *0.15 / float(user_info.weight)
    result = round(result,2)

    if result < 0.02:
        params['condition'] = 'シラフ'
        params['message'] = '<font color="green">このアプリを通じて楽しいお酒の飲み方を覚えましょう!</font>'
    elif result < 0.05 :
        params['condition'] = '爽快期'
        params['message'] = '<font color="skyblue">お酒はとても楽しいですね。ほどほどに...</font>'
        params['detail1'] = 'さわやかな気分になる'
        params['detail2'] = '皮膚が赤くなる'
        params['detail3'] = '陽気になる'
        params['detail4'] = '判断力が少しにぶる'
    elif result < 0.1 :
        params['condition'] = 'ほろ酔い期'
        params['message'] = '<font color="blue">お酒との付き合い方が上手い方はここらへんで飲むのをやめます。</font>'
        params['detail1'] = '手の動きが活発になる'
        params['detail2'] = '抑制がとれる（理性が失われる）'
        params['detail3'] = '体温が上がる'
        params['detail4'] = '脈が速くなる'
    elif result < 0.15 :
        params['condition'] = '酩酊初期'
        params['message'] = '<font color="purple">これ以上飲むと取り返しのつかないことになり兼ねます。注意しましょう。</font>'
        params['detail1'] = '気が大きくなる'
        params['detail2'] = '大声でがなりたてる'
        params['detail3'] = 'おこりっぽくなる'
        params['detail4'] = '立てばふらつく'
    elif result < 0.3 :
        params['condition'] ='酩酊期'
        params['message'] = '<font color="magenta">人に迷惑をかけます。今すぐ帰る準備をしましょう。</font>'
        params['detail1'] = '何度も同じことをしゃべる'
        params['detail2'] = '千鳥足になる'
        params['detail3'] = '呼吸が速くなる'
        params['detail4'] = '吐き気、おう吐がおこる'
    elif result < 0.4 :
        params['condition'] = '泥酔期'
        params['message'] = '<font color="pink">記憶できない状態です。お酒をやめましょう。</font>'
        params['detail1'] = 'まともに立てない'
        params['detail2'] = '意識がはっきりしない'
        params['detail3'] = '言語がめちゃめちゃになる'
    else :
        params['condition'] = '昏睡期'
        params['message'] = '<font color="red">命が危険です！お酒をやめてください!!!</font>'
        params['detail1'] = 'ゆり動かしても起きない'
        params['detail2'] = '大小便はたれ流しになる'
        params['detail3'] = '呼吸はゆっくりと深い'
        params['detail4'] = '死亡'

    return render(request, 'myapp/database.html', params)

prj/myapp/templates/myapp/database.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="ja">

<head>
  <link rel="shortcut icon" href="{% static 'prj/img/beer.jpeg' %}">
  <meta charset="utf-8">
  <title>お酒管理</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
  crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'prj/css/displayData.css'%}"/>
  <link rel="stylesheet" href="{% static 'prj/css/button.css' %}">
  <link rel="stylesheet" href="{% static 'prj/css/styles.css' %}">

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>

<body>

  <header class="header">
    <i id="open_menu" class="fas fa-bars"></i>
    <nav id="menu">
      <i id="close_menu" class="fas fa-times"></i>

      <ul>
        <li>
          <a href="{% url 'myapp:home' %}"><i class = "fas fa-home fa-2x"></i></a>
        </li>
        <li>
          <a href="{% url 'myapp:User_View' %}"><i class = "fas fa-user fa-2x"></i></a>
        </li>
        <li>
          <a href="{% url 'myapp:database' %}"><i class = "fas fa-list-alt fa-2x"></i></a>
        </li>
        <li>
          <a href="{% url 'myapp:HowtoUse_View' %}"><i class = "fas fa-cog fa-2x"></i></a>
        </li>

      </ul>
    </nav>
    <script src="{% static 'prj/js/menu.js' %}"></script>

    <h1>{{condition}}</h1>
    {{message|safe}}

  </div>
</header>
<section class="demo">

  <dl class="list maki">
    <form action="{% url 'myapp:delete' %}" method="post">
      {% csrf_token %}
      <button  type="submit">
        <i  id = "trash" class="fas fa-trash fa-2x fa-fw"></i>
      </button>


    </form>
    <dt align="center">
      飲んだものリスト
    </dt>

    <dt>
      <tr>
        <th>　名前　　</th>
        <th>度数(%)　　　</th>
        <th>量(ml)</th>
      </tr>
    </dt>
    {% for item in data %}
    <dd>
      <span>{{item.name}}</span>
      <span>{{item.degree}}</span>
      {{item.value}}
    </dd>
    {% endfor %}

  </dl>


  <a href="#" class="toggle">リストの開閉</a>

</section>


<script src="{% static 'prj/js/displayData.js'%}"></script>
</body>
</html>

prj/myapp/templates/myapp/home.html
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <link rel="shortcut icon" href="{% static 'prj/img/beer.jpeg' %}">
  <meta charset="utf-8">
  <title>お酒管理</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
  crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'prj/css/button.css' %}">
  <link rel="stylesheet" href="{% static 'prj/css/bubble.css' %}">
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<h1>alcohol manager</h1>
<div class="panel">
  <a href="{% url 'myapp:home' %}">
    <button>
      <i class="fas fa-home fa-4x fa-fw"></i>
    </button>
  </a>
  <a href="{% url 'myapp:User_View' %}">
    <button>
      <i class="fas fa-user fa-4x fa-fw"></i>
    </button>
  </a>
  <a href="{% url 'myapp:database' %}">
    <button>
      <i class="fas fa-list-alt fa-4x fa-fw"></i>
    </button>
  </a>
  <a href="{% url 'myapp:HowtoUse_View' %}">
    <button>
      <i class="fas fa-cog fa-4x fa-fw"></i>
    </button>
  </a>
</div>

<div class="panel borderless">
  <form action="" method="POST" enctype="multipart/form-data" style="display: inline">
    {% csrf_token %}
    <button>
    <i id ="upload" class="fas fa-camera-retro fa-4x fa-fw"></i>
  </button>
    {{ form.image}}
    <button  type="submit" accept="image/">
      <i class="far fa-paper-plane fa-4x fa-fw"></i>
    </button>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script>
  $('i#upload').click(function () {
    $('input[type="file"]').trigger('click');
  });
  </script>

  <a href="{% url 'myapp:Input_View' %}">
    <button>
      <i class="fas fa-pencil-alt fa-4x fa-fw"></i>
    </button>
  </a>

</div>

<div class="container">
  <div class="bubble-wrap">
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
  </div>
</div>


</html>

prj/myapp/templates/myapp/howtouse.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <link rel="shortcut icon" href="{% static 'prj/img/beer.jpeg' %}">
  <meta charset="utf-8">
  <title>お酒管理</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
  crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'prj/css/styles.css' %}">
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>
  <header>
    <div class="container">
      <i id="open_menu" class="fas fa-bars"></i>
      <nav id="menu">
        <i id="close_menu" class="fas fa-times"></i>

        <ul>
          <li>
            <a href="{% url 'myapp:home' %}"><i class = "fas fa-home fa-2x"></i></a>
          </li>
          <li>
            <a href="{% url 'myapp:User_View' %}"><i class = "fas fa-user fa-2x"></i></a>
          </li>
          <li>
            <a href="{% url 'myapp:database' %}"><i class = "fas fa-list-alt fa-2x"></i></a>
          </li>
          <li>
            <a href="{% url 'myapp:HowtoUse_View' %}"><i class = "fas fa-cog fa-2x"></i></a>
          </li>

        </ul>
      </nav>
      <h1>使用方法</h1>

    </div>
  </header>

  <section class="features">
    <div class="container">
      <h1>アプリの使い方</h1>
      <li>まず、ユーザ情報から身体情報を登録しておいてください。 </li>
      <li>ユーザー情報にある項目を入力してください。</li>
      <li>入力された情報を元に、あなたの身体の情報を表示します。</li>

      <p>お酒の飲み過ぎを予防するアプリです。
        <br>あくまでも推測によるものなので、目安としてご使用ください。</p>

      </section>

      <section class="features">
        <div class="container">
          <h1>白石麻衣</h1>
          <section class="feature">
            <img src="{% static 'prj/img/maiyan.jpg' %}">
            <p>言いたいことがあるんだよ やっぱり〇〇はかわいいよ すきすき大好き、やっぱ好き やっと見つけたお姫様 俺が生まれてきた理由 それは〇〇に出会うため 俺と一緒に人生歩もう 世界で一番愛してる ア・イ・シ・テ・ル</p>
          </section>

          <script src="{% static 'prj/js/menu.js' %}"></script>
        </body>

        </html>

prj/myapp/templates/myapp/inputform.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <link rel="shortcut icon" href="{% static 'prj/img/beer.jpeg' %}">
  <meta charset="utf-8">
  <title>お酒管理</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
  crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'prj/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'prj/css/input2.css' %}">
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>

<body>



  <div id="form-main">
    <div id="form-div">

      <p1>入力フォーム</p1>

      <p class="name">
        <i class="fas fa-beer"></i>
      </p>

      <script>
      if("{{result}}" != ""){
        document.write("{{result}}と判別されました")
      }
      </script>

      <form action="{% url 'myapp:Input_View' %}" method="post">
        {% csrf_token %}
        <label>お酒の種類</label>
        {{ form.name }}
        <p>{{ form.name.help_text }}</p>
        <label>度数</label>
        {{ form.degree }}
        <p>{{ form.degree.help_text }}</p>
        <label>量(ml)</label>
        {{ form.value }}
        <p>{{ form.value.help_text }}</p>

        <div class="submit">
          <input type="submit" value="登録" id="button-blue">
        </form>
        <div class="ease"></div>
      </div>


    </div>
    <header>
      <div class="container">
        <i id="open_menu" class="fas fa-bars"></i>
        <nav id="menu">
          <i id="close_menu" class="fas fa-times"></i>
          <ul>
            <li>
              <a href="{% url 'myapp:home' %}">
                <i class="fas fa-home fa-2x"></i>
              </a>
            </li>
          </ul>

        </nav>
      </div>
    </header>
    <script src="{% static 'prj/js/menu.js' %}"></script>

  </body>
  </html>

prj/myapp/templates/myapp/nowloading.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <link rel="shortcut icon" href="{% static 'prj/img/beer.jpeg' %}">
    <meta charset="utf-8">
    <title>お酒管理</title>
    <link rel="stylesheet" href="{% static 'prj/css/loading.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="refresh" content="4;{% url 'myapp:Input_View' %}">
</head>
<div id="loader">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
</div>
<!-- <script src="{% static 'prj/js/loading.js' %}">
 </script> -->

</html>

prj/myapp/templates/myapp/user.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <link rel="shortcut icon" href="{% static 'prj/img/beer.jpeg' %}">
  <meta charset="utf-8">
  <title>お酒管理</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
  crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'prj/css/styles.css' %}">
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>


<body>
  <header>
    <div class="container">
      <i id="open_menu" class="fas fa-bars"></i>
      <!--<nav id="menu" class="shown">-->
      <nav id="menu">
        <i id="close_menu" class="fas fa-times"></i>
        <ul>
          <li>
            <a href="{% url 'myapp:home' %}"><i class = "fas fa-home fa-2x"></i></a>
          </li>
          <li>
            <a href="{% url 'myapp:User_View' %}"><i class = "fas fa-user fa-2x"></i></a>
          </li>
          <li>
            <a href="{% url 'myapp:database' %}"><i class = "fas fa-list-alt fa-2x"></i></a>
          </li>
          <li>
            <a href="{% url 'myapp:HowtoUse_View' %}"><i class = "fas fa-cog fa-2x"></i></a>
          </li>

        </ul>

      </nav>
      <h1>ユーザー情報</h1>
    </div>
  </header>

  <section class="features">
    <form action="{% url 'myapp:User_View' %}" method="post">
      {% csrf_token %}
      <div class="container">
        <p>生年月日　
          <input type="date">

        </p>
        <p>身長
          <input type="number" name="number" min="100" max="200">

        </p>

        <label>体重</label>
        {{ form_weight.weight }}
        <p>{{ form_weight.weight.help_text }}</p>

        <label>年齢</label>
        {{ form_weight.age }}
        <p>{{ form_weight.age.help_text }}</p>
        <tr><td></td><td><input type="submit" value="保存"></td></tr>
      </div>



    </form>
  </section>

  <script src="{% static 'prj/js/menu.js' %}"></script>
</body>

</html>